### ISSUE TITLE
Improve registry review process with more checks

### ISSUE THREAD

**Issue by Xaroz** [hyperlane-xyz/hyperlane-registry#439]
We’re getting a lot of PRs against the registry, both from 1st and 3rd parties. We need to distribute the review load and build tools + tests to automate some of the work. The current process + tooling creates more work for PR reviewers and submitters than is necessary. 

From: https://www.notion.so/hyperlanexyz/Registry-review-process-and-issues-11a6d35200d6803499c4e0067ffbb45a

Currently we don’t have coverage for these common mistakes which need to be caught manually

```[tasklist]
### Tasks
- [x] 1. Invalid or unsuitable chain logo file
- [x] 2. Incorrect file paths
- [x] 3. Invalid chain data
- [x] 4. Invalid Warp configs
- [ ] 5. Missing or invalid changeset level
- [x] 6. Run `combine` job and `optimize` job on every commit to main
```
